--to create blip (you can change coordinate, blip, name everything here)
Citizen.CreateThread(function()
    Dealer = AddBlipForCoord(vector3(791.4, -758.72, 26.75))
    SetBlipSprite (Dealer, 488)
    SetBlipDisplay(Dealer, 4)
    SetBlipScale  (Dealer, 0.75)
    SetBlipAsShortRange(Dealer, true)
    SetBlipColour(Dealer, 3)
    BeginTextCommandSetBlipName('STRING')
    AddTextComponentSubstringPlayerName('Pizzeria')
    EndTextCommandSetBlipName(Dealer)
end)